INSERT INTO burgers (burger_name, devoured) VALUES ('Classic American Burger', FALSE);
INSERT INTO burgers (burger_name, devoured) VALUES ('Fire Hot Burger', TRUE);
INSERT INTO burgers (burger_name, devoured) VALUES ('Grilled Pineapple Burger', FALSE);
INSERT INTO burgers (burger_name, devoured) VALUES ('Texan BBQ Burger', FALSE);
INSERT INTO burgers (burger_name, devoured) VALUES ('Full-stack Burger', TRUE);
INSERT INTO burgers (burger_name, devoured) VALUES ('Farmhouse Burger', TRUE);
INSERT INTO burgers (burger_name, devoured) VALUES ('Ultimate Cheeseburger', FALSE);
INSERT INTO burgers (burger_name, devoured) VALUES ('Chicken Burger', FALSE);
INSERT INTO burgers (burger_name, devoured) VALUES ('Portobella Burger', TRUE);
INSERT INTO burgers (burger_name, devoured) VALUES ('Gluten-free Burger', FALSE);
